model:
  type: iHJMicro
  p: 0.01
  q: 0.005
  h1: 0.2
  h2: 0.2
  a1: 0.2
  a1_a2_ratio: 1.0
  gamma:
    - from: 1.0
      to: 2.0
      num: 3
  eta: 1.0

initial:
  A0: 0.5
  B0: 0.2

numerical:
  nx: 8192
  domain_length: 20  # [m]
  end_time: 25.0e-3  # [s]
  nt: 3

solver:
  atol: 1.0e-8
  rtol: 1.0e-8

characteristic_sizes:
  c0: 171.4       # [m/s]
  rho0: 4.107e-3  # [g/m^2]
  l: 1.0e-2       # [m]
